# Generated by Django 3.2.8 on 2021-11-10 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('courseCode', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=40)),
                ('courseTitle', models.CharField(max_length=255)),
                ('courseDesc', models.CharField(max_length=4095)),
                ('courseCreds', models.CharField(max_length=255)),
                ('coursePrereqs', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('courseCode', 'department', 'courseTitle', 'courseDesc', 'courseCreds', 'coursePrereqs'),
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('contents', models.CharField(max_length=1000)),
                ('Classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Classes+', to='api.classes')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
