# Generated by Django 3.2.8 on 2021-10-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('classCode', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=255)),
                ('classDesc', models.CharField(max_length=4095)),
                ('classCreds', models.CharField(max_length=255)),
                ('classPrereqs', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('classCode', 'className', 'classDesc', 'classCreds', 'classPrereqs'),
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('contents', models.CharField(max_length=1000)),
                ('Classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Classes+', to='test.classes')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
